import './sass/style.scss';
import getImg from './js/gallery';
import { onBurgerClick, onCloseClick } from './js/nav.js';
import getMap from './js/map.js';
import getSliderRange from './js/explore.js';
import getWelcomeSwiper from './js/welcome-swiper.js';
import { getYoutubeSwiper, getVideoInputs, getVideoVolumes } from './js/video-swiper.js';
import { videoButtons } from './js/video.js';
import pictureUp from './js/gallery-up';

getImg();
onBurgerClick();
onCloseClick();
getMap();
getSliderRange();
getWelcomeSwiper();
getYoutubeSwiper();
getVideoVolumes();
getVideoInputs();
videoButtons();
pictureUp();
